In [1]:
import tensorflow as tf
sess = tf.Session()
tens1 = tf.constant([[[1,2],[2,3]],[[3,4],[5,6]]])
print (sess.run(tens1)[1,1,0])

5


In [2]:
import tensorflow as tf
import numpy as np
x = tf.constant(np.random.rand(32).astype(np.float32))
y= tf.constant ([1,2,3])
x
y

<tf.Tensor 'Const_2:0' shape=(3,) dtype=int32>

In [3]:
import tensorflow as tf #we import tensorflow
import numpy as np #we import numpy
sess = tf.Session() #start a new Session Object
x_data = np.array([[1.,2.,3.],[3.,2.,6.]]) # 2x3 matrix
x = tf.convert_to_tensor(x_data, dtype=tf.float32) 
print (x)

Tensor("Const_3:0", shape=(2, 3), dtype=float32)


In [4]:
import tensorflow as tf
g = tf.Graph()
with g.as_default():
    import tensorflow as tf
    sess = tf.Session()
    W_m = tf.Variable(tf.zeros([10, 5]))
    x_v = tf.placeholder(tf.float32, [None, 10])
    result = tf.matmul(x_v, W_m)
print (g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }


In [5]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0]])
y = tf.constant([[4, -7, 4, -3, 4],[6, 4,-7, 4, 7],[2, 3, 2, 1, 4],[1, 5, 5, 5, 2]])
floatx = tf.constant([[2., 5., 3., -5.],[0., 3.,-2., 5.],[4., 3., 5., 3.],[6., 1., 4., 0.]])
tf.transpose(x).eval() # Transpose matrix

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]])

In [6]:
tf.matmul(x, y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]])

In [7]:
tf.matrix_determinant(floatx).eval()

818.0

In [8]:
tf.matrix_inverse(floatx).eval()

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.28117359, -0.18092909],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]], dtype=float32)

In [9]:
tf.matrix_solve(floatx, [[1],[1],[1],[1]]).eval()

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)

In [10]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[1, 2, 3],[3, 2, 1],[-1,-2,-3]])
boolean_tensor = tf.constant([[True, False, True],[False, False, True],[True, False, False]])
tf.reduce_prod(x, reduction_indices=1).eval() 

array([ 6,  6, -6])

In [11]:
tf.reduce_min(x, reduction_indices=1).eval()

array([ 1,  1, -3])

In [12]:
tf.reduce_max(x, reduction_indices=1).eval() 

array([ 3,  3, -1])

In [13]:
tf.reduce_mean(x, reduction_indices=1).eval()

array([ 2,  2, -2])

In [14]:
tf.reduce_all(boolean_tensor, reduction_indices=1).eval()

array([False, False, False], dtype=bool)

In [15]:
tf.reduce_any(boolean_tensor, reduction_indices=1).eval()

array([ True,  True,  True], dtype=bool)

In [16]:
import tensorflow as tf
In [2]: sess = tf.InteractiveSession()
In [3]: seg_ids = tf.constant([0,1,1,2,2]); # Group indexes : 0|1,2|3,4
In [4]: tens1 = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0],[6, 1, 4, 0]]) # A sample constant matrix
tf.segment_sum(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]])

In [17]:
tf.segment_prod(tens1, seg_ids).eval()

array([[  2,   5,   3,  -5],
       [  0,   9, -10,  15],
       [ 36,   1,  16,   0]])

In [18]:
tf.segment_min(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  3],
       [ 6,  1,  4,  0]])

In [19]:
tf.segment_max(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]])

In [20]:
tf.segment_mean(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]])

In [21]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0]])
listx = tf.constant([1,2,3,4,5,6,7,8])
listy = tf.constant([4,5,8,9])
boolx = tf.constant([[True,False], [False,True]])
tf.argmin(x, 1).eval()

array([3, 2, 1, 3], dtype=int64)

In [22]:
tf.argmax(x, 1).eval()

array([1, 3, 2, 0], dtype=int64)

In [23]:
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]], dtype=int64)

In [24]:
tf.unique(listx)[0].eval()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
tf.setdiff1d(listx, listy)[0].eval()

array([1, 2, 3, 6, 7])

In [26]:
import tensorflow as tf
sess = tf.InteractiveSession()
x = tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1, 4, 0]])
tf.shape(x).eval() # Shape of the tensor

array([4, 4])

In [27]:
tf.size(x).eval()

16

In [28]:
tf.rank(x).eval()

2

In [29]:
tf.reshape(x, [8, 2]).eval()

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]])

In [30]:
tf.squeeze(x).eval()

array([[ 2,  5,  3, -5],
       [ 0,  3, -2,  5],
       [ 4,  3,  5,  3],
       [ 6,  1,  4,  0]])

In [31]:
tf.expand_dims(x,1).eval()

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]])

In [32]:
import tensorflow as tf
sess = tf.InteractiveSession()
t_matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
t_array = tf.constant([1,2,3,4,9,8,6,5])
t_array2= tf.constant([2,3,4,5,6,7,8,9])
tf.slice(t_matrix, [1, 1], [2,2]).eval()

array([[5, 6],
       [8, 9]])

In [35]:
*tf.split(axis=0, num_or_size_splits=2, value=t_array) 

[<tf.Tensor 'split_1:0' shape=(4,) dtype=int32>,
 <tf.Tensor 'split_1:1' shape=(4,) dtype=int32>]

In [36]:
tf.tile([1,2],[3]).eval()

array([1, 2, 1, 2, 1, 2])

In [37]:
tf.pad(t_matrix, [[0,1],[2,1]]).eval()

array([[0, 0, 1, 2, 3, 0],
       [0, 0, 4, 5, 6, 0],
       [0, 0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0]])

In [39]:
*tf.concat(axis=0, values=[t_array, t_array2]).eval()

array([1, 2, 3, 4, 9, 8, 6, 5, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
*tf.stack([t_array, t_array2]).eval()

array([[1, 2, 3, 4, 9, 8, 6, 5],
       [2, 3, 4, 5, 6, 7, 8, 9]])

In [43]:
*sess.run(tf.unstack(t_matrix)) 

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [44]:
tf.reverse(t_matrix, [False,True]).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [45]:
import tensorflow as tf
sess = tf.Session()
filename_queue =tf.train.string_input_producer(tf.train.match_filenames_once("./blue_jay.jpg"))
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)
image=tf.image.decode_jpeg(value)
flipImageUpDown=tf.image.encode_jpeg(tf.image.flip_up_down(image))
flipImageLeftRight=tf.image.encode_jpeg(tf.image.flip_left_right(image))
tf.global_variables_initializer().run(session=sess)
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(coord=coord, sess=sess)
example = sess.run(flipImageLeftRight)
print (example)
file=open ("flippedUpDown.jpg", "wb+")
file.write (flipImageUpDown.eval(session=sess))
file.close()
file=open ("flippedLeftRight.jpg", "wb+")
file.write (flipImageLeftRight.eval(session=sess))
file.close()

b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x01,\x01,\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x05\x88\x07\x80\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\x97\x98\x9